config/routes.rb
Rails.application.routes.draw do
  root    'application#index'

  get     'login'               => 'sessions#index'
  post    'login'               => 'sessions#login'

  get     'signup'              => 'users#index'
  
  delete  'logout'              => 'application#logout'

  post    'create_room'         => 'application#create_room'
  post    'add_friend'          => 'application#add_friend'
  post    'post_question'       => 'application#post_question'
  post    'post_comment'        => 'application#post_comment'
  post    'send_message'        => 'application#send_message'
  post    'switch_room'         => 'application#switch_room'
  post    'like_comment'        => 'application#like_comment'
  post    'unlike_comment'      => 'application#unlike_comment'

  resources :users, only:[:new,:create]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :question, :class_name => 'Question'
	belongs_to :user, :class_name => 'User'
	has_many :likes, dependent: :destroy
	
	validates :user_id, presence: true
	validates :question_id, presence: true
	validates :body, presence: true
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user, :class_name => 'User'
	belongs_to :friend, :class_name => 'User'

	def self.add_friend(user_id, friend_id)

		friend = Friendship.create(user_id: user_id, friend_id: friend_id)
		friend
	end
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user, :class_name => 'User'
	belongs_to :comment, :class_name => 'Comment'

	validates_uniqueness_of :user_id, :scope => [:comment_id]
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user, :class_name => 'User'
	belongs_to :room, :class_name => 'Room'

	validates :user_id, presence: true
	validates :room_id, presence: true
	validates :body, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :user, :class_name => 'User'
	belongs_to :room, :class_name => 'Room'
	has_many :comments, dependent: :destroy

	validates :user_id, presence: true
	validates :room_id, presence: true
	validates :body, presence: true
	
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :questions, dependent: :destroy
	has_many :messages, dependent: :destroy
	belongs_to :owner, :class_name => 'User'

	validates_uniqueness_of :owner_id, :scope => [:room_name]
	validates :room_name, :owner_id, presence: true

	def self.create_room(room_name, owner_id)
    	return false if Room.where(room_name: room_name, owner_id: owner_id).to_a.size > 0

    	room = Room.create(room_name: room_name, owner_id: owner_id)
    	room
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rooms, :class_name => 'Room', :foreign_key => 'owner_id', dependent: :destroy
  has_many :users, :class_name => 'Friendship', :foreign_key => 'friend_id', dependent: :destroy
  has_many :friends, :class_name => 'Friendship', :foreign_key => 'user_id', dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  
  validates :username, presence: true, uniqueness: true
  validates :password_hash, presence: true
  validates :salt, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_uniqueness_of :first_name, :scope => [:last_name]

  def self.create_user(username, password, password_confirm, first_name, last_name)
    return false if password != password_confirm
    return false if User.where(username: username).to_a.size > 0

    salt = BCrypt::Engine.generate_salt
    hashed_password = BCrypt::Engine.hash_secret(
      password, salt)
    new_user = User.create(username: username,
        password_hash: hashed_password, salt: salt, first_name: first_name, last_name: last_name)
    new_user
  end

  def self.authenticate(username, password)
    user = User.where(username: username).first
    if user.present? && user.password_hash == BCrypt::Engine.hash_secret(password, user.salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login
  respond_to :html, :js

  include SessionsHelper, ApplicationHelper

  def index
    @room = Room.new

    @friend = Friendship.new
    
    update

  end

  def logout
      exit if entered?
      log_out if logged_in?
      redirect_to login_path
  end

  
  def create_room
    @room = current_user.rooms.create!(room_name: params[:cr][:room_name])
    
    update
  end

  def add_friend
    f = User.where(first_name: params[:af][:first_name],
                          last_name: params[:af][:last_name]).to_a.first
    @friend = current_user.friendships.create(friend_id: f.id)
    
    update
  end

  def post_question
    body = params[:pq][:body]
    Question.create(user_id: current_user.id, room_id: current_room.id, body: body)
    @questions = current_room.questions
  end

  def post_comment
    body = params[:pc][:body]
    question = Question.find_by(id: params[:pc][:question_id])
    Comment.create(user_id: current_user.id, question_id: question.id, body: body)
    @questions = current_room.questions
  end
  
  def send_message
    body = params[:sm][:body]
    Message.create(user_id: current_user.id, room_id: current_room.id, body: body)
    @messages = current_room.messages

  end

  def switch_room
    session[:room_id] = params[:sr][:room_id]
    @questions = current_room.questions
    @messages = current_room.messages
  end

  def like_comment
    comment_id = params[:comment_id]
    Like.create(user_id: current_user.id, comment_id: comment_id)
    @questions = current_room.questions
  end

  def unlike_comment
    comment_id = params[:comment_id]
    Like.find_by(user_id: current_user.id, comment_id: comment_id).destroy
    
    @questions = current_room.questions
  end

  private

    def require_login
    	redirect_to login_path if session[:user_id].nil?
    end

    def update
      @rooms = current_user.rooms

      @friends = Array.new

      friendships = current_user.friendships + current_user.users

      friendships.each do |f|
        if f.friend.id == current_user.id
          @friends.push(f.user)
          @rooms += f.user.rooms
        else
          @friends.push(f.friend)
          @rooms += f.friend.rooms
        end
      end

      if entered?
        @questions = current_room.questions
        @messages = current_room.messages
      end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_before_action :require_login
	respond_to :html, :js

	include SessionsHelper
	
	def index

	end

	def login
		user = User.authenticate(params[:session][:username], params[:session][:password])
	    if user
	      # Log the user in and redirect to the user's show page.
	      log_in user
	    else
	      # Create an error message.
	      	flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
	    end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	skip_before_action :require_login
  	respond_to :html, :js

  	def index
  		@user = User.new
  	end

   	def create
   		p = user_params

    	@user = User.create_user(p[:username], 
    	p[:password], p[:password_confirmation],
    	p[:first_name], p[:last_name])
 		
  	end

  	private

    	def user_params
      		params.require(:user).permit(:username, 
      			:password, :password_confirmation, 
            	:first_name, :last_name)
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_room
		@current_room ||= Room.find_by(id: session[:room_id])
 	end

  def entered?
  	if !session[:room_id].nil?
  		!current_room.nil?
  	else
  		false
  	end
	end

  def exit
  	session.delete(:room_id)
   	@current_room = nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
	
end

app/views/application/_discussion_room.html.erb
<% if entered? %>
	<%= current_room.room_name %>
	<!-- ask and answer question area-->
	<div id='question_area' style="height:200px;width:200px;border:1px solid red;overflow-y: scroll;">
		<%= render 'questions/questions' %>
	</div>
	<div id="post_question">
		<%= render 'questions/question_form' %>
	</div>

	<!-- chat area-->
	<div id="chat_area" style="height:200px;width:200px;border:1px solid red; overflow-y: scroll;">
		<%= render 'messages/messages' %>
	</div>
	<div id="send_message">
		<%= render 'messages/message_form' %>
	</div>
<% end %>

app/views/application/add_friend.js.erb
<% if @friend %>
	$("#friendlist-list").html("<%= escape_javascript(render 'friends/friend') %>")
<% else %>
	<% flash[:danger] = "Friend exist."%>
<% end %>
$("#add-friend-form").html("<%= escape_javascript(render 'friends/add_friend') %>")

app/views/application/create_room.js.erb
<% if @room %>
	$("#roomlist-list").html("<%= escape_javascript(render 'rooms/room') %>")
<% else %>
	<% flash[:danger] = "Room exist."%>
<% end %>
$("#create-room-form").html("<%= escape_javascript(render 'rooms/create_room') %>")

app/views/application/index.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>
<header>
	<span>Hello, <%= current_user.first_name %></span>
	<br>
	<%= link_to "Log out", logout_path, method: :delete %>
</header>

<div id="roomlist">
	<div class="somesection">ROOMS</div>
	<div id="roomlist-list">
		<%= render 'rooms/room' %>
	</div>
	<div id="create-room-form">
		<%= render 'rooms/create_room' %>
	</div>
</div>

<div id="maincontainer" >
	<%= render 'discussion_room' %>
</div>

<div id="friendslist">
	<div class="somesection">FRIENDS</div>
	<ul id="friendlist-list">
		<%= render 'friends/friend' %>
	</ul>
	<div id="add-friend-form">
		<%= render 'friends/add_friend' %>
	</div>
</div>

app/views/application/like_comment.js.erb
$('#question_area').html("<%= escape_javascript(render 'questions/questions') %>")

app/views/application/post_comment.js.erb
$('#question_area').html("<%= escape_javascript(render 'questions/questions') %>")

app/views/application/post_question.js.erb
$('#question_area').html("<%= escape_javascript(render 'questions/questions') %>")
$('#post_question').html("<%= escape_javascript(render 'questions/question_form') %>");

app/views/application/send_message.js.erb
$('#chat_area').html("<%= escape_javascript(render 'messages/messages') %>")
$('#send_message').html("<%= escape_javascript(render 'messages/message_form') %>")

app/views/application/switch_room.js.erb
$('#maincontainer').html("<%= escape_javascript(render 'discussion_room') %>")

app/views/application/unlike_comment.js.erb
$('#question_area').html("<%= escape_javascript(render 'questions/questions') %>")

app/views/friends/_add_friend.html.erb
<%= form_for :af, url: add_friend_path, autocomplete: :off, remote: true do |f| %>
	<%= f.text_field :first_name, placeholder: "Fisrt name" %>
	<%= f.text_field :last_name, placeholder: "Last name" %>
	<%= f.submit "Add friend" %>
<% end %>

app/views/friends/_friend.html.erb
<% @friends.each do |f| %>
	<li> <%= f.last_name %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuizbeeWeb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	
<%= yield %>

</body>
</html>

app/views/messages/_message_form.html.erb
<%= form_for :sm, url: send_message_path, remote: true do |q| %>
	<%= q.text_field :body, placeholder: "Chat here" %>
	<%= q.submit "Send" %>
<% end %>

app/views/messages/_messages.html.erb
<ul>
	<% @messages.each do |message| %>
		<li>
			<%= message.user.last_name + ':'+ message.body %>
		</li>
	<% end %>
</ul>

app/views/questions/_question_form.html.erb
<%= form_for :pq, url: post_question_path, remote: true do |q| %>
	<%= q.text_field :body, placeholder: "Enter the question" %>
	<%= q.submit "Post question" %>
<% end %>

app/views/questions/_questions.html.erb
<ul>
	<% @questions.each do |question| %>
		<li>
			<%= question.body %>

			<ul>
				<% question.comments.each do |comment|%>
					<li> <%= comment.user.last_name + ':' + comment.body %></li>
					<br>
					Likes:<%= comment.likes.size %>
					<% if Like.where(user_id: current_user.id, comment_id: comment.id).size == 0 %>
						<%= link_to "Like", like_comment_path(:comment_id => comment.id), method: :post, remote: true %>
					<% else %>
						<%= link_to "Unlike", unlike_comment_path(:comment_id => comment.id), method: :post, remote: true %>
					<% end %>
				<% end %>
			</ul>
			<%= form_for :pc, url: post_comment_path, remote: true do |c| %>
				<%= c.text_field :body, placeholder: "Enter the answer" %>
				<%= c.hidden_field :question_id, :value => question.id %>
				<%= c.submit "Post comment" %>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/rooms/_create_room.html.erb
<%= form_for :cr, url: create_room_path, autocomplete: :off, remote: true do |r| %>
	<%= r.text_field :room_name, placeholder: "Create room" %>
	<%= r.submit "Create room" %>
<% end %>

app/views/rooms/_room.html.erb
<ul>
	<% @rooms.each do |r| %>
		<li> 
			<%= r.room_name %> 
			<%= form_for :sr, url: switch_room_path, remote: true do |s| %>
				<%= s.hidden_field :room_id, :value => r.id %>
				<%= s.submit "Switch room" %>
			<% end %>
		</li>
	<% end %>
</ul>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user, remote: true do |f| %>
	
    <%= f.label :username %>
    <%= f.text_field :username %>
    <br>
      		
    <%= f.label :password %>
    <%= f.password_field :password %>
	<br>
      		
    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, minlength: 3 %>
    <br>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <br>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <br>

	<%= f.submit "Sign up" %>
<% end %>

<%= link_to "Cancel", login_path %>

app/views/users/create.js.erb
<% if @user %>
	<% if @user.valid? %>
		window.location.replace("<%= root_path %>");
	<% else %>
		$(".sign-up-error").html("<%= escape_javascript(render 'shared/error_messages') %>")
	<% end %>
<% else  %>
	$(".sign-up-error").html("Username used or password doesn't match with confirmation!")
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="sign-up-error">
    <%= render 'shared/error_messages' %>
</div>

<div class="sign-up-form">
  	<%= render 'form' %>
</div>